### ISSUE TITLE
Compilation and build error when executing make on MacOS

### ISSUE THREAD

**Issue by madabhushipb** [coin-or/GAMSlinks#1]
Hello! I'm running into the following compilation errors (see attached log) when executing the make command on macOS. The solver that I am trying to use is IPOPT, which compiled and was built successfully.
[make_err.log](https://github.com/coin-or/GAMSlinks/files/8409862/make_err.log)

**Comment by svigerske** [comment]
It looks like C++11 is not enabled by default in your compiler. Try configure with `ADD_CXXFLAGS=-std=c++11` as argument.

**Comment by madabhushipb** [comment]
Thank you! That helped.
